# Список команд, которые нужно скрыть.
hidden-commands:
  - "op"
  - "pl"
  - "plugins"
  - "stop"

# Разрешение, при наличии которого игрок видит / может выполнять скрытые команды
permission-to-bypass: "cloverhide.bypass"

# Нужно ли скрывать команды в табе?
hide-in-tab-complete: true

# Сообщения плагина (все в формате списка, чтобы удобно редактировать многострочные варианты)
messages:
  no-permission:
    - "&cУ вас нет прав для использования этой команды!"

  command-not-found:
    - "&cТакой команды не существует!"
    - "&7Проверьте правильность ввода или перечень доступных команд!"